export const REGISTER_USER = 'REGISTER_USER'
export const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER'
export const FAIL_REGISTER_USER = 'FAIL_REGISTER_USER'

export const LOGIN_USER = 'LOGIN_USER'
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER'
export const FAIL_LOGIN_USER = 'FAIL_LOGIN_USER'

export const SET_IS_AUTH = 'SET_IS_AUTH'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'

export const CREATE_BLOG = 'CREATE_BLOG'
export const SUCCESS_CREATE_BLOG = 'SUCCESS_CREATE_BLOG'
export const FAIL_CREATE_BLOG = 'FAIL_CREATE_BLOG'

export const GET_ALL_BLOGS = 'GET_ALL_BLOGS'
export const SUCCESS_GET_ALL_BLOGS = 'SUCCESS_GET_ALL_BLOGS'
export const FAIL_GET_ALL_BLOGS = 'FAIL_GET_ALL_BLOGS'

export const GET_USER_BLOGS='GET_USER_BLOGS'
export const SUCCESS_GET_USER_BLOGS='SUCCESS_GET_USER_BLOGS'
export const FAIL_GET_USER_BLOGS='FAIL_GET_USER_BLOGS'



